# -*- coding: utf-8 -*-
"""loteria_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2mNKIslLeLneuIb2Lo0f54ZEXBBfRRw

# Prevendo números da loteria com TensorFlow
Este notebook contém um exemplo de como usar o TensorFlow para prever números de loteria com base em dados anteriores.

### Carregando bibliotecas
"""

import tensorflow as tf
import numpy as np
import pandas as pd

"""### Carregando os dados da loteria (arquivo CSV de exemplo)"""

data = pd.read_csv('loteria_exemplo.csv', sep=";")
data.head()  # Visualizando as primeiras linhas do arquivo CSV

"""### Preparando os dados para o treinamento"""

# Separando as entradas (X) e saídas (Y)
X = data[['X1', 'X2', 'X3', 'X4', 'X5', 'X6']].values  # Entradas
Y = data[['Y1', 'Y2', 'Y3', 'Y4', 'Y5', 'Y6']].values  # Saídas

# Normalizando os dados
X = X / 50.0  # Entradas normalizadas
Y = Y / 50.0  # Saídas normalizadas

"""### Definindo o modelo de rede neural"""

model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(6,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(6)
])

# Compilando o modelo
model.compile(optimizer='adam', loss='mean_squared_error')

"""### Treinando o modelo"""

model.fit(X, Y, epochs=500, verbose=1)

"""### Fazendo uma previsão"""

# Exemplo de entrada (6 números)
entrada = np.array([[5, 12, 23, 34, 45, 50]])
entrada_normalizada = entrada / 50.0  # Normalizando a entrada

# Fazendo a previsão
predicao = model.predict(entrada_normalizada)

# Convertendo de volta para a escala original (0 a 50)
predicao = predicao * 50.0
print('Números previstos:', predicao)